// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: api/gpu_scheduler.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GPUScheduler_SubmitTask_FullMethodName    = "/algogpu.GPUScheduler/SubmitTask"
	GPUScheduler_GetTaskStatus_FullMethodName = "/algogpu.GPUScheduler/GetTaskStatus"
	GPUScheduler_CancelTask_FullMethodName    = "/algogpu.GPUScheduler/CancelTask"
	GPUScheduler_GetGPUStatus_FullMethodName  = "/algogpu.GPUScheduler/GetGPUStatus"
	GPUScheduler_TaskEvents_FullMethodName    = "/algogpu.GPUScheduler/TaskEvents"
)

// GPUSchedulerClient is the client API for GPUScheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GPUSchedulerClient interface {
	// 提交任务
	SubmitTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	// 查询任务状态
	GetTaskStatus(ctx context.Context, in *TaskStatusRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error)
	// 取消任务
	CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error)
	// 获取 GPU 状态
	GetGPUStatus(ctx context.Context, in *GetGPUStatusRequest, opts ...grpc.CallOption) (*GPUStatusResponse, error)
	// 任务结果流
	TaskEvents(ctx context.Context, in *TaskEventsRequest, opts ...grpc.CallOption) (GPUScheduler_TaskEventsClient, error)
}

type gPUSchedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewGPUSchedulerClient(cc grpc.ClientConnInterface) GPUSchedulerClient {
	return &gPUSchedulerClient{cc}
}

func (c *gPUSchedulerClient) SubmitTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, GPUScheduler_SubmitTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUSchedulerClient) GetTaskStatus(ctx context.Context, in *TaskStatusRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error) {
	out := new(TaskStatusResponse)
	err := c.cc.Invoke(ctx, GPUScheduler_GetTaskStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUSchedulerClient) CancelTask(ctx context.Context, in *CancelTaskRequest, opts ...grpc.CallOption) (*CancelTaskResponse, error) {
	out := new(CancelTaskResponse)
	err := c.cc.Invoke(ctx, GPUScheduler_CancelTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUSchedulerClient) GetGPUStatus(ctx context.Context, in *GetGPUStatusRequest, opts ...grpc.CallOption) (*GPUStatusResponse, error) {
	out := new(GPUStatusResponse)
	err := c.cc.Invoke(ctx, GPUScheduler_GetGPUStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gPUSchedulerClient) TaskEvents(ctx context.Context, in *TaskEventsRequest, opts ...grpc.CallOption) (GPUScheduler_TaskEventsClient, error) {
	stream, err := c.cc.NewStream(ctx, &GPUScheduler_ServiceDesc.Streams[0], GPUScheduler_TaskEvents_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &gPUSchedulerTaskEventsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type GPUScheduler_TaskEventsClient interface {
	Recv() (*TaskEvent, error)
	grpc.ClientStream
}

type gPUSchedulerTaskEventsClient struct {
	grpc.ClientStream
}

func (x *gPUSchedulerTaskEventsClient) Recv() (*TaskEvent, error) {
	m := new(TaskEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GPUSchedulerServer is the server API for GPUScheduler service.
// All implementations must embed UnimplementedGPUSchedulerServer
// for forward compatibility
type GPUSchedulerServer interface {
	// 提交任务
	SubmitTask(context.Context, *TaskRequest) (*TaskResponse, error)
	// 查询任务状态
	GetTaskStatus(context.Context, *TaskStatusRequest) (*TaskStatusResponse, error)
	// 取消任务
	CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error)
	// 获取 GPU 状态
	GetGPUStatus(context.Context, *GetGPUStatusRequest) (*GPUStatusResponse, error)
	// 任务结果流
	TaskEvents(*TaskEventsRequest, GPUScheduler_TaskEventsServer) error
	mustEmbedUnimplementedGPUSchedulerServer()
}

// UnimplementedGPUSchedulerServer must be embedded to have forward compatible implementations.
type UnimplementedGPUSchedulerServer struct {
}

func (UnimplementedGPUSchedulerServer) SubmitTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SubmitTask not implemented")
}
func (UnimplementedGPUSchedulerServer) GetTaskStatus(context.Context, *TaskStatusRequest) (*TaskStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTaskStatus not implemented")
}
func (UnimplementedGPUSchedulerServer) CancelTask(context.Context, *CancelTaskRequest) (*CancelTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTask not implemented")
}
func (UnimplementedGPUSchedulerServer) GetGPUStatus(context.Context, *GetGPUStatusRequest) (*GPUStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGPUStatus not implemented")
}
func (UnimplementedGPUSchedulerServer) TaskEvents(*TaskEventsRequest, GPUScheduler_TaskEventsServer) error {
	return status.Errorf(codes.Unimplemented, "method TaskEvents not implemented")
}
func (UnimplementedGPUSchedulerServer) mustEmbedUnimplementedGPUSchedulerServer() {}

// UnsafeGPUSchedulerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GPUSchedulerServer will
// result in compilation errors.
type UnsafeGPUSchedulerServer interface {
	mustEmbedUnimplementedGPUSchedulerServer()
}

func RegisterGPUSchedulerServer(s grpc.ServiceRegistrar, srv GPUSchedulerServer) {
	s.RegisterService(&GPUScheduler_ServiceDesc, srv)
}

func _GPUScheduler_SubmitTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUSchedulerServer).SubmitTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUScheduler_SubmitTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUSchedulerServer).SubmitTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUScheduler_GetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUSchedulerServer).GetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUScheduler_GetTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUSchedulerServer).GetTaskStatus(ctx, req.(*TaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUScheduler_CancelTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUSchedulerServer).CancelTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUScheduler_CancelTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUSchedulerServer).CancelTask(ctx, req.(*CancelTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUScheduler_GetGPUStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGPUStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GPUSchedulerServer).GetGPUStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GPUScheduler_GetGPUStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GPUSchedulerServer).GetGPUStatus(ctx, req.(*GetGPUStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GPUScheduler_TaskEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(TaskEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GPUSchedulerServer).TaskEvents(m, &gPUSchedulerTaskEventsServer{stream})
}

type GPUScheduler_TaskEventsServer interface {
	Send(*TaskEvent) error
	grpc.ServerStream
}

type gPUSchedulerTaskEventsServer struct {
	grpc.ServerStream
}

func (x *gPUSchedulerTaskEventsServer) Send(m *TaskEvent) error {
	return x.ServerStream.SendMsg(m)
}

// GPUScheduler_ServiceDesc is the grpc.ServiceDesc for GPUScheduler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GPUScheduler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "algogpu.GPUScheduler",
	HandlerType: (*GPUSchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTask",
			Handler:    _GPUScheduler_SubmitTask_Handler,
		},
		{
			MethodName: "GetTaskStatus",
			Handler:    _GPUScheduler_GetTaskStatus_Handler,
		},
		{
			MethodName: "CancelTask",
			Handler:    _GPUScheduler_CancelTask_Handler,
		},
		{
			MethodName: "GetGPUStatus",
			Handler:    _GPUScheduler_GetGPUStatus_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "TaskEvents",
			Handler:       _GPUScheduler_TaskEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/gpu_scheduler.proto",
}
