# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from api import gpu_scheduler_pb2 as api_dot_gpu__scheduler__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in api/gpu_scheduler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class GPUSchedulerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitTask = channel.unary_unary(
                '/algogpu.GPUScheduler/SubmitTask',
                request_serializer=api_dot_gpu__scheduler__pb2.TaskRequest.SerializeToString,
                response_deserializer=api_dot_gpu__scheduler__pb2.TaskResponse.FromString,
                _registered_method=True)
        self.GetTaskStatus = channel.unary_unary(
                '/algogpu.GPUScheduler/GetTaskStatus',
                request_serializer=api_dot_gpu__scheduler__pb2.TaskStatusRequest.SerializeToString,
                response_deserializer=api_dot_gpu__scheduler__pb2.TaskStatusResponse.FromString,
                _registered_method=True)
        self.CancelTask = channel.unary_unary(
                '/algogpu.GPUScheduler/CancelTask',
                request_serializer=api_dot_gpu__scheduler__pb2.CancelTaskRequest.SerializeToString,
                response_deserializer=api_dot_gpu__scheduler__pb2.CancelTaskResponse.FromString,
                _registered_method=True)
        self.GetGPUStatus = channel.unary_unary(
                '/algogpu.GPUScheduler/GetGPUStatus',
                request_serializer=api_dot_gpu__scheduler__pb2.GetGPUStatusRequest.SerializeToString,
                response_deserializer=api_dot_gpu__scheduler__pb2.GPUStatusResponse.FromString,
                _registered_method=True)
        self.TaskEvents = channel.unary_stream(
                '/algogpu.GPUScheduler/TaskEvents',
                request_serializer=api_dot_gpu__scheduler__pb2.TaskEventsRequest.SerializeToString,
                response_deserializer=api_dot_gpu__scheduler__pb2.TaskEvent.FromString,
                _registered_method=True)


class GPUSchedulerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitTask(self, request, context):
        """提交任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTaskStatus(self, request, context):
        """查询任务状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelTask(self, request, context):
        """取消任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGPUStatus(self, request, context):
        """获取 GPU 状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskEvents(self, request, context):
        """任务结果流
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GPUSchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitTask': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitTask,
                    request_deserializer=api_dot_gpu__scheduler__pb2.TaskRequest.FromString,
                    response_serializer=api_dot_gpu__scheduler__pb2.TaskResponse.SerializeToString,
            ),
            'GetTaskStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTaskStatus,
                    request_deserializer=api_dot_gpu__scheduler__pb2.TaskStatusRequest.FromString,
                    response_serializer=api_dot_gpu__scheduler__pb2.TaskStatusResponse.SerializeToString,
            ),
            'CancelTask': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelTask,
                    request_deserializer=api_dot_gpu__scheduler__pb2.CancelTaskRequest.FromString,
                    response_serializer=api_dot_gpu__scheduler__pb2.CancelTaskResponse.SerializeToString,
            ),
            'GetGPUStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGPUStatus,
                    request_deserializer=api_dot_gpu__scheduler__pb2.GetGPUStatusRequest.FromString,
                    response_serializer=api_dot_gpu__scheduler__pb2.GPUStatusResponse.SerializeToString,
            ),
            'TaskEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.TaskEvents,
                    request_deserializer=api_dot_gpu__scheduler__pb2.TaskEventsRequest.FromString,
                    response_serializer=api_dot_gpu__scheduler__pb2.TaskEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'algogpu.GPUScheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('algogpu.GPUScheduler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class GPUScheduler(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algogpu.GPUScheduler/SubmitTask',
            api_dot_gpu__scheduler__pb2.TaskRequest.SerializeToString,
            api_dot_gpu__scheduler__pb2.TaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTaskStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algogpu.GPUScheduler/GetTaskStatus',
            api_dot_gpu__scheduler__pb2.TaskStatusRequest.SerializeToString,
            api_dot_gpu__scheduler__pb2.TaskStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algogpu.GPUScheduler/CancelTask',
            api_dot_gpu__scheduler__pb2.CancelTaskRequest.SerializeToString,
            api_dot_gpu__scheduler__pb2.CancelTaskResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetGPUStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/algogpu.GPUScheduler/GetGPUStatus',
            api_dot_gpu__scheduler__pb2.GetGPUStatusRequest.SerializeToString,
            api_dot_gpu__scheduler__pb2.GPUStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/algogpu.GPUScheduler/TaskEvents',
            api_dot_gpu__scheduler__pb2.TaskEventsRequest.SerializeToString,
            api_dot_gpu__scheduler__pb2.TaskEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
